steps:
  # 1. Build container image using GCP Buildpack
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sibo:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--env=GOOGLE_RUNTIME_VERSION=3.13.1'

  # 2. Deploy built container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sibo'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sibo:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sibo:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
