import os
import tempfile
from typing import Dict, Any, List
from fpdf import FPDF


class SIBORepdf(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(24, 76, 120)  # Dark Blue
        self.cell(0, 10, "SIBO-Friendly Restaurant Guide", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_draw_color(200, 200, 200)
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by SIBO Assistant Bot", align="C")


def clean_text(text: str) -> str:
    """Replaces non-latin or unsupported unicode characters for standard FPDF fonts."""
    if not text:
        return ""
    # Map common currency & symbols
    text = text.replace("€", "EUR ").replace("£", "GBP ").replace("¥", "JPY ")
    # Encode/decode latin1 safe
    return text.encode("latin-1", "replace").decode("latin-1")


def render_restaurant_section(pdf: SIBORepdf, title: str, restaurants: List[Dict[str, Any]]):
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 116, 166)  # Blue section header
    pdf.cell(0, 10, clean_text(title), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    if not restaurants:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, "No restaurants found for this category.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)
        return

    for idx, rest in enumerate(restaurants, 1):
        name = clean_text(rest.get("name", "Unknown Restaurant"))
        rating = clean_text(rest.get("rating", "N/A"))
        price_lvl = clean_text(rest.get("price_level", "N/A"))
        address = clean_text(rest.get("address", "N/A"))

        # Restaurant Header Card
        pdf.set_fill_color(240, 244, 248)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(0, 8, f" {idx}. {name}  |  Rating: {rating}  |  Price: {price_lvl}", fill=True, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 6, f"   Address: {address}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # SIBO Meals List
        meals = rest.get("sibo_meals", [])
        if meals:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 5, "   Recommended SIBO-Friendly Meals:", new_x="LMARGIN", new_y="NEXT")

            for meal in meals:
                m_name = clean_text(meal.get("meal_name", "Meal"))
                m_price = clean_text(meal.get("price", "N/A"))
                m_rationale = clean_text(meal.get("sibo_rationale", ""))
                m_waiter = clean_text(meal.get("waiter_instructions", ""))

                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(40, 40, 40)
                pdf.multi_cell(0, 5, f"   - {m_name} ({m_price})")

                if m_rationale:
                    pdf.set_font("Helvetica", "", 9)
                    pdf.set_text_color(70, 70, 70)
                    pdf.multi_cell(0, 4.5, f"     Why SIBO-safe: {m_rationale}")

                if m_waiter:
                    pdf.set_font("Helvetica", "I", 9)
                    pdf.set_text_color(180, 40, 40)  # Red accent for waiter instructions
                    pdf.multi_cell(0, 4.5, f"     Waiter note: \"{m_waiter}\"")

                pdf.ln(1)
        pdf.ln(4)


def generate_sibo_pdf(data: Dict[str, Any]) -> str:
    """
    Generates a PDF file from Gemini SIBO restaurant data and returns the absolute temp file path.
    """
    pdf = SIBORepdf()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    city = clean_text(data.get("city", "Unknown City"))
    query_meal = clean_text(data.get("query_meal_type", "General Menu"))

    # Subheader
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, f"Target City: {city}  |  Search Focus: {query_meal}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    # Top Rating Section
    top_rating = data.get("top_rating", [])
    render_restaurant_section(pdf, "1. Top 5 Best Restaurants by Rating", top_rating)

    # Top Price Section
    top_price = data.get("top_price", [])
    render_restaurant_section(pdf, "2. Top 5 Best Restaurants by Price", top_price)

    # Write PDF to temp file
    temp_dir = tempfile.gettempdir()
    filename = f"SIBO_Guide_{city.replace(' ', '_')}.pdf"
    filepath = os.path.join(temp_dir, filename)

    pdf.output(filepath)
    return filepath
